name: deploy gh-pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build web
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: ./web/pnpm-lock.yaml
      - name: Build Wasm
        run: |
          cargo install wasm-pack
          wasm-pack build --target web --reference-types --weak-refs
      - name: Build Web
        run: |
          cd ./web
          pnpm install
          pnpm run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./web/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


